name: pytest_legacy_python
on: [pull_request, push]
jobs:
  lint_legacy_python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'
      - run: pip install pytest
      - run: pip install -e .
      - run: pytest . || true
      - run: pytest --doctest-modules . || true
